FROM php:8.2-fpm

ARG UID
ARG GID

ENV UID=${UID}
ENV GID=${GID}

RUN addgroup --system --gid ${GID} gabrielteixeira
RUN adduser --system --home /bin/sh --no-create-home --uid ${UID} --ingroup gabrielteixeira --disabled-login --disabled-password gabrielteixeira

RUN sed -i 's/user = www-data/user = gabrielteixeira/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/group = www-data/group = gabrielteixeira/g' /usr/local/etc/php-fpm.d/www.conf

RUN chown -R ${UID}:${GID} /var/www/html

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN apt-get update && apt-get install -y \
    git \
    libzip-dev \
    unzip \
    libpq-dev \
    libpng-dev \
    libmagickwand-dev \
    && docker-php-ext-install pdo pdo_pgsql zip \
    && docker-php-ext-install gd \
    && docker-php-ext-enable gd

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions @composer pdo_pgsql

# Install and run compose
RUN curl -sS https://getcomposer.org/installer | /usr/local/bin/php -- --install-dir=/usr/local/bin --filename=composer

#RUN composer install --no-interaction --optimize-autoloader

EXPOSE 9000

USER gabrielteixeira
