FROM nginx:1.25

ARG UID
ARG GID

ENV UID=${UID}
ENV GID=${GID}

RUN addgroup --system --gid ${GID} gabrielteixeira
RUN adduser --system --home /bin/sh --no-create-home --uid ${UID} --ingroup gabrielteixeira --disabled-login --disabled-password gabrielteixeira
RUN sed -i 's/user  nginx/user gabrielteixeira/g' /etc/nginx/nginx.conf

COPY . /var/www/html

RUN chown -R ${UID}:${GID} /var/www/html
